// 数据库操作语句合集
let UserSQL = {
  selectUser: 'SELECT * FROM userregister WHERE uid = ?',
  checkLogin: 'SELECT uid FROM userregister WHERE uid = ? AND urpsw = ?',
  insertUser: 'INSERT INTO userregister(uid,urpsw) VALUES(?,?)',
  insertUserInfo: 'INSERT INTO userinfo(uid,uname) VALUES(?,?)',
  deleteUser: 'DELETE FROM userregister WHERE uid = ?',
  updateUserPsw: 'UPDATE userregister SET urpsw = ? WHERE uid = ?',
  getUserFriendList: 'SELECT * FROM userinfo INNER JOIN userfriend ON userfriend.uid = ? AND userfriend.ufriid = userinfo.uid ',
  getMyselfInfo: 'SELECT * FROM userinfo WHERE uid = ?',
  selectUserFriend: 'SELECT uname,uid FROM userinfo WHERE uname LIKE ? OR uid LIKE ?',
  insertFriend: 'INSERT INTO userfriend(uid,ufriid) VALUES(?,?)',
  checkMyFriend: 'INSERT INTO applyFriend(fromid, toid, applyMethod, formTable) VALUES(?,?,?,?)',
  getGroupList: 'SELECT grouplist.gid,grouplist.uid,gname,glogo,gNotice FROM grouplist INNER JOIN groupconnect ON groupconnect.uid = ? AND groupconnect.gid = grouplist.gid',
  changeFriendShip: 'UPDATE userfriend SET ufInfo = ?,ufStyle = ? WHERE uid = ? AND ufriid = ?',
  getFriendShip: 'SELECT ufInfo,ufStyle FROM userfriend WHERE uid = ? AND ufriid = ?',
  deleteFriend: 'DELETE FROM userfriend WHERE uid = ? AND ufriid = ?',
  getGroupInfo: 'SELECT gname,uid,glogo,gNotice FROM grouplist WHERE gid = ?',
  checkInGroup: 'SELECT * FROM groupconnect WHERE gid = ? AND uid = ?',
  getGroupMember: 'SELECT groupconnect.uid, userinfo.uname, userinfo.ulogo FROM groupconnect INNER JOIN grouplist INNER JOIN userinfo ON grouplist.gid = ? AND groupconnect.gid = grouplist.gid AND groupconnect.uid = userinfo.uid',
  getGroupMaster: 'SELECT userinfo.uid,userinfo.uname,userinfo.ulogo FROM grouplist INNER JOIN userinfo ON gid = ? AND grouplist.uid = userinfo.uid',
  insertGroup: 'INSERT INTO groupconnect(gid,uid) VALUES(?,?)',
  exitGroup: 'DELETE FROM groupconnect WHERE gid = ? AND uid = ?',
  newGroup: 'INSERT INTO grouplist(gname,uid,glogo,gNotice,gtime) VALUES(?,?,?,?,?)',
  deleteGroup: 'DELETE FROM grouplist,groupconnect USING grouplist,groupconnect WHERE groupconnect.gid = ? AND grouplist.uid = ? AND grouplist.gid = groupconnect.gid',
  changeGroupMessage: 'UPDATE grouplist SET gname = ?,glogo = ?,gNotice = ? WHERE uid = ? AND gid = ?',
  changeGroupMaster: 'UPDATE grouplist SET uid = ? WHERE uid = ? AND gid = ?',
  deleteGroupMember: 'DELETE groupconnect FROM groupconnect, grouplist WHERE grouplist.gid = groupconnect.gid AND groupconnect.gid = ? AND grouplist.uid = ? AND groupconnect.uid = ? AND groupconnect.uid <> ?',
  changeMyself: 'UPDATE userinfo SET uname = ?,ulogo = ?,usex = ?,usign = ?,ucity = ? WHERE uid = ?',
  getApplyFriend: 'SELECT * FROM applyfriend WHERE fromid = ?',
  getOtherApplyFriend: 'SELECT * FROM applyfriend WHERE toid = ?',
  getFriendTrend: 'SELECT utNo,userfriend.uid, userinfo.uname,userinfo.ulogo,utText,utTime FROM usertrend INNER JOIN (userfriend INNER JOIN userinfo) ON userfriend.uid = ? AND userfriend.ufriid = userinfo.uid AND userfriend.ufriid = usertrend.uid',
  getFriendTrendReply: 'SELECT rNo,rStyle,rid,buid,userinfo.uid,ruid,rContent,rTime,userinfo.uname as uname FROM trend INNER JOIN userinfo WHERE ruid = userinfo.uid AND rStyle = ? AND rid = ?',
  deleteMyselfTrend: 'DELETE FROM usertrend WHERE uid = ? AND utNo = ?',
  getVoteTotal: 'SELECT vGood,vBad FROM vote WHERE utNo = ? AND vStyle = ?',
  getMyselfVote: 'SELECT vState FROM vote WHERE utNo = ? AND uid = ? AND vStyle = ?',
  replyOther: 'INSERT INTO reply(rStyle,rid,buid,ruid,rContent,rTime) VALUES(?,?,?,?,?,?)',
  setMyselfVote: 'INSERT INTO vote(uid,vState,vStyle) VALUES(?,?,?)',
  changeMyselfVote: 'UPDATE vote vState WHERE utNo = ? AND uid = ? AND vStyle = ?',
  deleteReply: 'DELETE FROM reply WHERE rNo = ? AND rid = ? AND ruid = ?',
  getMyNewGroup: 'SELECT gid FROM grouplist WHERE uid = ? AND gtime = ?',
  getSingleMessage: 'SELECT * FROM usersinglemessage WHERE uid = ?',
  setSingleMessage: 'INSERT INTO usersinglemessage(uid,fromid,toid,usmMessage,usmTime) VALUES(?,?,?,?,?)',
  getGroupMessage: 'SELECT * FROM groupmessage WHERE gid = ? AND uid = ?',
  setGroupMessage: 'INSERT INTO groupmessage(gid,uid,fromid,gmContent,gmTime) VALUES(?,?,?,?,?)'
};
module.exports = UserSQL;